name: koi_api
description: the api wrapper of koi service
version: 0.0.1
# homepage: https://github.com/boyan01/flutter-netease-music

publish_to: none

environment:
  sdk: ">=2.14.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  http: ^0.13.3
  dio_cookie_manager: ^2.1.1
  cookie_jar: ^3.0.1
  dio_http2_adapter: ^2.0.0
  shared_preferences: ^2.0.7
  path_provider: ^2.1.1

  json_annotation: ^4.8.1
  equatable: ^2.0.3
  music_api:
    path: ../music_api/
  netease_api:
    path: ../netease_api/

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  build_runner: ^2.1.5
  json_serializable: ^6.7.1

